version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rails-chat
    ports:
      - "5431:5432"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/rails-chat-tutorial"
    ports:
      - "3002:3000"
    depends_on:
      - db
    links:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: rails-chat
  redis:
    image: redis
    command: redis-server
    ports:
      - "6378:6379"